server.port=${PORT:5103}

grader.support-files-dir=${SUPPORT_FILES_DIR:../grader/support-files}
grader.expected-outputs-dir=${EXPECTED_OUTPUTS_DIR:../grader/expected_outputs}
grader.temp-dir=${TEMP_DIR:build/temp}
