server.port=${PORT:5103}

grader.support-files-dir=${SUPPORT_FILES_DIR:assets/support-files}
grader.expected-outputs-dir=${EXPECTED_OUTPUTS_DIR:assets/expected_outputs}
grader.temp-dir=${TEMP_DIR:build/temp}
